argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  crds:
    # -- this fixes CustomResourceDefinition "applications.argoproj.io" in namespace "" exists error
    install: false
